name: flumen_passwd
version: 1.0.0
description: PBKDF2 password hashing utility

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  lint: ^1.5.0
  test: ^1.16.5
