name: flumen_config
version: 0.1.0
description: A safe and convenient way to read YAML configuration files.

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flumen_runtime: ^0.1.0
  meta: '>=1.0.0 <1.3.0'
  yaml: '>=2.1.8 <3.0.0'

dev_dependencies:
  test: ^1.3.0
