name: flumen_isolator
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
version: 1.0.0
repository: https://github.com/flumenframework/flumen

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  analyzer: '>=0.32.0 <0.41.0'

dev_dependencies:
  test: ^1.3.0
  test_package:
    path: test/test_package
